### ISSUE TITLE
vec3/mat3 operator overloads

### ISSUE THREAD

**Issue by fprotais** [ssloy/ultimaille#11]
Operators "*=", "-=", "+=" and "/=" are not defined with double. Would be really helpful.

**Comment by ssloy** [comment]
-= and += with double??

**Comment by fprotais** [comment]
Yeah probably not, not very standard. But -= vec3 would be a nice addition thought.

**Comment by ssloy** [comment]
implemented here
https://github.com/ssloy/ultimaille/commit/495e27f7c17ed871a23d553dee3fc5f544b5f765
