### ISSUE TITLE
Add of a prev_around_vertex method in SurfaceConnectivity

### ISSUE THREAD

**Issue by david540** [ssloy/ultimaille#12]
Turning counter clockwise around a vertex with next_around_vertex is often sufficient, but we sometimes want to turn clockwise.
This operation is just `next(opposite(corner_id))`.
The problem is that we need to handle the case `fec.opposite(corner_id) == -1`, I propose to return -1 in this case.
Something like 
`
int SurfaceConnectivity::prev_around_vertex(const int corner_id) const {
    return opposite(corner_id) == -1 ? -1 : next(opposite(corner_id));
}
`

**Comment by ssloy** [comment]
done here:
https://github.com/ssloy/ultimaille/commit/e11a9c1f4c60b800ec0930b36b3b1bbf488cdeeb
