### ISSUE TITLE
is_boundary_vert(const int v) not working if no neighbour

### ISSUE THREAD

**Issue by david540** [ssloy/ultimaille#15]
The current version is 
`
bool SurfaceConnectivity::is_boundary_vert(const int v) const {
        int cir = v2c[v];
        if (cir < 0) return false;
        do {
            if (opposite(cir) == -1) return true;
            cir = c2c[cir];
        } while (cir != v2c[v]);
        return false;
    }
    `
This produce a segfault if `c2c[cir] == -1` (in this case it means we are on a boundary vert)
    
I propose to handle this segfault by returning true if `cir == -1` during the loop
   `
bool SurfaceConnectivity::is_boundary_vert(const int v) const {
        int cir = v2c[v];
        if(cir < 0) return false;
        do {
            if (cir == -1) return true;
            if (opposite(cir) == -1) return true;
            cir = c2c[cir];
        } while (cir != v2c[v]);
        return false;
    }`

**Comment by ssloy** [comment]
Attends, mais si c'est un sommet isolé, il doit sortir avec la condition `if (cir<0) return false;` ??

**Comment by david540** [comment]
non c'est quand t'es en 2D plat, sur les bords à un moment tu as c2c[c] == -1 même si le sommet n'est pas isolé

**Comment by david540** [comment]
attends je vais retester voir si j'ai un segfault avec l'ancienne version

**Comment by ssloy** [comment]
> non c'est quand t'es en 2D plat, sur les bords à un moment tu as c2c[c] == -1 même si le sommet n'est pas isolé

pas sensé ! normalement c2c doit faire le tour malgré les bords

**Comment by david540** [comment]
J'ai effectivement un segfault avec l'ancienne version de is_boundary_vert

**Comment by ssloy** [comment]
comprends pas, c'est quoi l'ancienne version?
