### ISSUE TITLE
Add default empty constructor to HBoxes

### ISSUE THREAD

**Issue by fprotais** [ssloy/ultimaille#19]
Currently, the only way to use HBoxes as a member of class is through a pointer (if you want to initialise the bboxes with the class). **A default empty constructor with a mean to set the bboxes afterward** would be nice.

**Comment by ssloy** [comment]
try this commit

https://github.com/ssloy/ultimaille/commit/34ea33944b75264b9f5bb5b4e5d1dc94f0ad6170
