### ISSUE TITLE
Il manque les instances de write_vtk avec les mesh génériques. Pixel-dev ne compile pas sans ca.

### ISSUE THREAD

**Issue by gloook** [ssloy/ultimaille#24]
Il faut ajouter dans vtp.cpp et les entêtes dans vtk.h.
Eventuellement le code des fonctions est juste un message d'erreur: pas grave ;)

void write_vtk(const std::string filename, const Surface& m, const SurfaceAttributes attr) {
        write_vtk_format(filename, m, attr);
    }
    void write_vtk(const std::string filename, const Volume& m, const VolumeAttributes attr) {
        write_vtk_format(filename, m, attr);
    }

**Comment by ssloy** [comment]
fixed here 7664a0e162bd00bd23c9d7e2a7442fd2b8554df4
